name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build and unit test only
        run: |
          xcodebuild \
            -project "Lamp & Light  Lamp & Light.xcodeproj" \
            -scheme "Lamp & Light  Lamp & Light" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            -only-testing:"Lamp___Light__Lamp___LightTests" \
            clean test 