name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s "$(mdfind 'kMDItemCFBundleIdentifier == "com.apple.dt.Xcode" && kMDItemVersion >= "15.4"' | head -n 1)"
      - name: Build and test
        run: |
          xcodebuild \
            -project "Lamp & Light  Lamp & Light.xcodeproj" \
            -scheme "Lamp & Light  Lamp & Light" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            clean test 